#!/bin/sh
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=4:mem=20gb
#PBS -J 2000-2022

cd $HOME/git/ERA5-grids-into-national-subnational-boundaries-Worldwide/
module load anaconda3/personal
python $HOME/git/ERA5-grids-into-national-subnational-boundaries-Worldwide/prog/01_extract_netcdf/downloading_netcdf_files_day_sep_era5_cdsapi.py ${PBS_ARRAY_INDEX}

# to run type
# qsub -q med-bio downloading_netcdf_files_day_sep_era5_cdsapi.run
# THIS WILL RUN ALL LATEST CHOSEN YEAR FOR ERA5 PROCESSING IN ALL COUNTRIES FOR ADM1