#!/bin/sh
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=4:mem=20gb
#PBS -J 1-23

cd $HOME/git/ERA5-grids-into-national-subnational-boundaries-Worldwide/
module load anaconda3/personal
R --slave --args ${PBS_ARRAY_INDEX} < $HOME/git/ERA5-grids-into-national-subnational-boundaries-Worldwide/prog/01_extract_netcdf/single_country_run_previous_years_adm2.R

# to run type
# qsub -q med-bio single_country_run_previous_years_adm2.run
# THIS WILL RUN PREVIOUS YEARS FOR ERA5 PROCESSING IN ALL COUNTRIES FOR ADM2